name: turkish
version: 0.1.0
authors:
- Ahmet A. Akın <ahmetaa@gmail.com>
- Mehmet D. Akın <mdakin@gmail.com>
description: Turkish String upper-lower case converter and comparator
homepage: https://github.com/ahmetaa/dotless_i
environment:
  sdk: '>=2.0.0-dev.19.0'
dev_dependencies:
  test: '>=0.12.30 <0.13.0'
