name: turkish
version: 0.2.1
description: Turkish String upper-lower case converter and comparators for sorting
homepage: https://github.com/ahmetaa/turkish
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: '>=1.16.0'
